let car = "sabaru";
console.log("is car == 'sabaru' ? i predict true.");
console.log(car == 'sabaru');
console.log("is car !== 'sabaru' ? i predict true.");
console.log(car !== 'sabaru');
console.log("is car == 'suzuki' ? i predict true.");
console.log(car == 'suzuki');
console.log("is car !== 'suzuki' ? i predict true.");
console.log(car !== 'suzuki');
console.log("is car == 'toyota' ? i predict true.");
console.log(car == 'toyota');
console.log("is car !== 'toyota' ? i predict true.");
console.log(car !== 'toyota');
console.log("is car == 'BMW' ? i predict true.");
console.log(car == 'BMW');
console.log("is car !== 'BMW' ? i predict true.");
console.log(car !== 'BMW');
console.log("is car == 'fond' ? i predict true.");
console.log(car == 'fond');
console.log("is car !== 'fond' ? i predict true.");
console.log(car !== 'fond');
