"use strict";
console.log("Enequality test :", "abdul rafay" === "abdul rafay");
console.log("Inequality test :", "hammad" !== "rafay");
console.log("lowercase test:", "ABDUL RAFAY".toLocaleLowerCase() === "abdul rafay");
console.log("Equality test :", 1000 === 1000);
console.log("Inequality test :", 100 !== 10);
console.log("Greater than test :", 200 > 20);
console.log("less than test:", 10000 < 100000);
console.log("Greater than and equal to test :", 10 >= 10);
console.log("less than and equal to test :", 5 <= 10);
console.log("And operator test:", true && true);
console.log("Or operator test:", true || false);
let car = [1, 2, 3];
console.log("test number:", car.includes(2));
console.log("test number2:", !car.includes(6));
